# Generated by Django 5.2.9 on 2025-12-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the TODO item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the TODO item', null=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='Due date for the TODO item', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', help_text='Status of the TODO item', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the TODO was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the TODO was last updated')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when the TODO was marked as resolved', null=True)),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'ordering': ['-created_at'],
            },
        ),
    ]
